config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :players
  resources :spaces
  root 'games#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord

  has_many :players
  has_many :spaces
  validates :name, presence: true, allow_blank: false

  def roll(players, dice)
    current_player = get_current_player
    current_player.move(dice.roll)
    update_position_for(current_player)
    winner = game_winner(current_player)
    change_turn(players)
  end

  def change_turn(players)    
    players = players.rotate
  end

  def get_current_player
    players.first
  end

  def perform(big_dependency)
    big_dependency.execute
    return "Game over man! Game over."
  end

  def update_position_for(current_player)
    space = spaces[current_player.read_attribute(:position) - 1]

    if space.destination
      current_player.position = space.destination
    end
  end

  def game_winner(current_player)
    if current_player.position == 100
      current_player
    end
  end


end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @game = Game.new
  end

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def create
    @game_workflow = CreatesGame.new(
      name: params[:game][:name]
    )
    @game_workflow.create

    if @game_workflow.game.errors.any?
      @game = @game_workflow.game
      render :new
    else
      redirect_to action: 'show', id: @game_workflow.game.id
    end
      
  end

end

app/helpers/games_helper.rb
module GamesHelper
  SPACESDATA = [
    {space_type: "empty", destination: nil}, # 1
    {space_type: "ladder", destination: 38}, # 2
    {space_type: "empty", destination: nil}, # 3
    {space_type: "empty", destination: nil}, # 4
    {space_type: "empty", destination: nil}, # 5
    {space_type: "empty", destination: nil}, # 6
    {space_type: "ladder", destination: 14}, # 7
    {space_type: "ladder", destination: 31}, # 8
    {space_type: "empty", destination: nil}, # 9
    {space_type: "empty", destination: nil}, # 10
    {space_type: "empty", destination: nil}, # 11
    {space_type: "empty", destination: nil}, # 12
    {space_type: "empty", destination: nil}, # 13
    {space_type: "empty", destination: nil}, # 14
    {space_type: "ladder", destination: 26}, # 15
    {space_type: "chute", destination: 6}, # 16
    {space_type: "empty", destination: nil}, # 17
    {space_type: "empty", destination: nil}, # 18
    {space_type: "empty", destination: nil}, # 19
    {space_type: "empty", destination: nil}, # 20
    {space_type: "ladder", destination: 42}, # 21
    {space_type: "empty", destination: nil}, # 22
    {space_type: "empty", destination: nil}, # 23
    {space_type: "empty", destination: nil}, # 24
    {space_type: "empty", destination: nil}, # 25
    {space_type: "empty", destination: nil}, # 26
    {space_type: "empty", destination: nil}, # 27
    {space_type: "ladder", destination: 84}, # 28
    {space_type: "empty", destination: nil}, # 29
    {space_type: "empty", destination: nil}, # 30
    {space_type: "empty", destination: nil}, # 31
    {space_type: "empty", destination: nil}, # 32
    {space_type: "empty", destination: nil}, # 33
    {space_type: "empty", destination: nil}, # 34
    {space_type: "empty", destination: nil}, # 35
    {space_type: "ladder", destination: 44}, # 36
    {space_type: "empty", destination: nil}, # 37
    {space_type: "empty", destination: nil}, # 38
    {space_type: "empty", destination: nil}, # 39
    {space_type: "empty", destination: nil}, # 40
    {space_type: "empty", destination: nil}, # 41
    {space_type: "empty", destination: nil}, # 42
    {space_type: "empty", destination: nil}, # 43
    {space_type: "empty", destination: nil}, # 44
    {space_type: "empty", destination: nil}, # 45
    {space_type: "chute", destination: 25}, # 46
    {space_type: "empty", destination: nil}, # 47
    {space_type: "empty", destination: nil}, # 48
    {space_type: "chute", destination: 11}, # 49
    {space_type: "empty", destination: nil}, # 50
    {space_type: "ladder", destination: 67}, # 51
    {space_type: "empty", destination: nil}, # 52
    {space_type: "empty", destination: nil}, # 53
    {space_type: "empty", destination: nil}, # 54
    {space_type: "empty", destination: nil}, # 55
    {space_type: "empty", destination: nil}, # 56
    {space_type: "empty", destination: nil}, # 57
    {space_type: "empty", destination: nil}, # 58
    {space_type: "empty", destination: nil}, # 59
    {space_type: "empty", destination: nil}, # 60
    {space_type: "empty", destination: nil}, # 61
    {space_type: "chute", destination: 19}, # 62
    {space_type: "empty", destination: nil}, # 63
    {space_type: "chute", destination: 60}, # 64
    {space_type: "empty", destination: nil}, # 65
    {space_type: "empty", destination: nil}, # 66
    {space_type: "empty", destination: nil}, # 67
    {space_type: "empty", destination: nil}, # 68
    {space_type: "empty", destination: nil}, # 69
    {space_type: "empty", destination: nil}, # 70
    {space_type: "empty", destination: nil}, # 71
    {space_type: "empty", destination: nil}, # 72
    {space_type: "empty", destination: nil}, # 73
    {space_type: "chute", destination: 53}, # 74
    {space_type: "empty", destination: nil}, # 75
    {space_type: "empty", destination: nil}, # 76
    {space_type: "empty", destination: nil}, # 77
    {space_type: "ladder", destination: 98}, # 78
    {space_type: "empty", destination: nil}, # 79
    {space_type: "empty", destination: nil}, # 80
    {space_type: "empty", destination: nil}, # 81
    {space_type: "empty", destination: nil}, # 82
    {space_type: "empty", destination: nil}, # 83
    {space_type: "empty", destination: nil}, # 84
    {space_type: "empty", destination: nil}, # 85
    {space_type: "empty", destination: nil}, # 86
    {space_type: "ladder", destination: 94}, # 87
    {space_type: "empty", destination: nil}, # 88
    {space_type: "chute", destination: 68}, # 89
    {space_type: "empty", destination: nil}, # 90
    {space_type: "empty", destination: nil}, # 91
    {space_type: "chute", destination: 88}, # 92
    {space_type: "empty", destination: nil}, # 93
    {space_type: "empty", destination: nil}, # 94
    {space_type: "chute", destination: 75}, # 95
    {space_type: "empty", destination: nil}, # 96
    {space_type: "empty", destination: nil}, # 97
    {space_type: "empty", destination: nil}, # 98
    {space_type: "chute", destination: 80}, # 99
    {space_type: "empty", destination: nil}, # 100
  ]

  def self.generate_spaces
    spaces = []
    SPACESDATA.each do |config|
      spaces << Space.new(config)
    end
    spaces
  end
end

app/views/games/index.html.erb
<h1>Games</h1>

<table>
  <thead>
    <tr>
      <td>Game Name</td>
      <td>Players</td>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>   
      <tr>
        <td><%= link_to game.name, action: "show", id: game.id %></td>
        <%game.players.each do |player| %>
          <td><%= player.name + ','%></td>
        <%end%>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/new.html.erb
<h1>Start a new Game</h1>
<%= form_for(@game) do |g| %>
  <%= g.label(:name) %>
  <%= g.text_field(:name) %>
  <%= g.submit %>
<% end %>

<%if @game.errors.any? %>
  <div id="errors">
    <h3>Game not created because:</h3>
    <ul>
      <% @game.errors.messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <h4>Please try again</h4>
<% end %>

app/views/games/show.html.erb
<h1>Game Display</h1>
<br />
<h3>Game Name: <%= @game.name %></h3>
<p>
Players: 
<br/>
<table>
  <thead>
    <tr>
      <td>
        Name
      </td>
      <td>
        ID
      </td>
      <td>
        Position
      </td>
    </tr>
  </thead>
  <tbody>
  <% @game.players.each do |player| %> 
  <tr>
    <td>
      <%=player.name %>
    </td>
    <td>
      <%=player.id%>
    </td>
    <td>
      <%=player.position%>
    </td>
  </tr>
  <%end%>
  <tr>
    <td>
      <button id='take turn' type='button' onClick="@game.roll(Dice.new(), @game.players)">roll dice</button>
    </td>
  </tr>
  </tbody>
</table>

</p>
<br>
<%= link_to '<button id="Add_Player type="button">Add a player</button>'.html_safe, new_player_path %>





<table>
  <thead>
    <tr>
      <%(0..8).each do%>
      <td>_________ </td>
      <%end%>
      <td>_________</td>
    </tr>
  </thead>
  <tbody>
    <% i = 1%>
    <% playerids = []%>
    <% @game.spaces.each do |space| %>
      <% @game.players.each do |player|%>
        <%playerids = []%>
        <% if player.position == i%>
          <% playerids << player.id%>
        <%end%>
      <%end%>

      <% spaces_after = i < 10 ? 6 : i < 100 ? 5 : 4%>
      <% if space.space_type != "empty" %>
        <% spaces_after_dest = space.destination >= 10 ? 3 : 4%>
      <%else%>
        <% spaces_after_dest = 3%>
      <% end %>
      <td><pre><%= "|"%><%= i%><%=" "*spaces_after%><%="|"%><br /></pre> 
             <pre><%="|  "%><%= space.space_type == "empty" ? "  " : space.destination%><%= " " * spaces_after_dest%><%="|"%><br /></pre>
             <pre>|<%playerids.each do |id|%><%=id%><%end%><%=" " * (7-playerids.size)%>|</pre>
             <pre><%="|       |"%><br /><%="`````````" %></pre>
      </td>    
      <% if i%10 == 0 %>
        <tr>
      <% end %>
      <% i+= 1%>
    <%end%>
  </tbody>
</table>